sudo: required
services:
    - docker

before_install:
   - docker build -t belghar/push_front -f Dockerfile.dev Dockerfile.dev

script:
- docker run -e CI=true belghar/push_front npm run test -- --coverage
