sudo: required
services:
    - docker
language: node_js
node_js:
  - 12
git:
  clone: true

before_install:
   - docker build -t belghar/push_front -f Dockerfile.dev .

script:
- docker run -e CI=true belghar/push_front npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "push_front"
   env: "PushFront-env"
   bucket_name: "elasticbeanstalk-us-east-2-154338466768"
   bucket_path: "push_front"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

