version: '3'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: push_front_dev
        volumes:
            - /app/node_modules
            - .:/app
        ports:
           - "3000:3000"
        stdin_open: true

    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: push_front_test
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true
        command: ["npm", "run", "test"]


    prod:
      build: .
      container_name: push_front_prod
      ports:
        - 8080:80
