FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN apk add --update \
  python \
  python-dev \
  py-pip \
  build-base \
  git \
  openssh-client \
&& pip install virtualenv \
&& rm -rf /var/cache/apk/*

RUN npm install

COPY . .

CMD ["npm", "run", "start"]
