/* LAYOUT */
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const ADD_APPLICATION_SUCCESS = 'ADD_APPLICATION_SUCCESS';
export const ADD_APPLICATION_FAILED = 'ADD_APPLICATION_FAILED';

export const EDIT_APPLICATION = 'EDIT_APPLICATION';
export const EDIT_APPLICATION_SUCCESS = 'EDIT_APPLICATION_SUCCESS';
export const EDIT_APPLICATION_FAILED = 'EDIT_APPLICATION_FAILED';

export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const DELETE_APPLICATION_SUCCESS = 'DELETE_APPLICATION_SUCCESS';
export const DELETE_APPLICATION_FAILED = 'DELETE_APPLICATION_FAILED';

export const LIST_APPLICATIONS = 'LIST_APPLICATIONS';
export const LIST_APPLICATIONS_SUCCESS = 'LIST_APPLICATIONS_SUCCESS';
export const LIST_APPLICATIONS_FAILED = 'LIST_APPLICATIONS_FAILED';

export const GET_APPLICATION_BY_ID = 'GET_APPLICATION_BY_ID';
export const GET_APPLICATION_BY_ID_SUCCESS = 'GET_APPLICATION_BY_ID_SUCCESS';
export const GET_APPLICATION_BY_ID_FAILED = 'GET_APPLICATION_BY_ID_FAILED';
