/* LAYOUT */
export const ADD_COMPANY = 'ADD_COMPANY';
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_FAILED = 'ADD_COMPANY_FAILED';

export const LIST_COMPANIES = 'LIST_COMPANIES';
export const LIST_COMPANIES_SUCCESS = 'LIST_COMPANIES_SUCCESS';
export const LIST_COMPANIES_FAILED = 'LIST_COMPANIES_FAILED';
