/* LAYOUT */
export const ADD_COMPANY = 'ADD_COMPANY';
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_FAILED = 'ADD_COMPANY_FAILED';

export const EDIT_COMPANY = 'EDIT_COMPANY';
export const EDIT_COMPANY_SUCCESS = 'EDIT_COMPANY_SUCCESS';
export const EDIT_COMPANY_FAILED = 'EDIT_COMPANY_FAILED';

export const LIST_COMPANIES = 'LIST_COMPANIES';
export const LIST_COMPANIES_SUCCESS = 'LIST_COMPANIES_SUCCESS';
export const LIST_COMPANIES_FAILED = 'LIST_COMPANIES_FAILED';

export const GET_COMPANY_BY_ID = 'GET_COMPANY_BY_ID';
export const GET_COMPANY_BY_ID_SUCCESS = 'GET_COMPANY_BY_ID_SUCCESS';
export const GET_COMPANY_BY_ID_FAILED = 'GET_COMPANY_BY_ID_FAILED';
